/**
 * Default editing templates for testing
 */

export const defaultTemplates = [
  {
    name: 'Tech Review',
    description: 'Fast-paced style with bold text overlays and quick cuts',
    textStyles: [
      {
        id: '1',
        name: 'Main Title',
        font: 'Arial Black, sans-serif',
        size: 64,
        color: '#ffffff',
        position: 'center',
        animation: 'scale',
        timing: { inDuration: 10, holdDuration: 45, outDuration: 10 },
        fontWeight: 'bold',
        textAlign: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        padding: 30,
        borderRadius: 12,
      },
      {
        id: '2',
        name: 'Lower Third',
        font: 'Arial, sans-serif',
        size: 36,
        color: '#00ff88',
        position: 'lowerThird',
        animation: 'slideLeft',
        timing: { inDuration: 12, holdDuration: 60, outDuration: 12 },
        fontWeight: 'bold',
        textAlign: 'left',
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        padding: 20,
        borderRadius: 8,
      },
      {
        id: '3',
        name: 'Emphasis Text',
        font: 'Impact, sans-serif',
        size: 52,
        color: '#ff3366',
        position: 'center',
        animation: 'bounce',
        timing: { inDuration: 15, holdDuration: 40, outDuration: 10 },
        fontWeight: 'bold',
        textAlign: 'center',
        backgroundColor: 'transparent',
        padding: 20,
        borderRadius: 0,
      },
    ],
    transitions: {
      type: 'fade',
      duration: 8,
      frequency: 4.5, // 4.5 cuts per minute
    },
    brollPatterns: {
      insertFrequency: 25,
      duration: 4,
      transitionIn: 'fade',
      transitionOut: 'fade',
    },
    pacing: {
      avgSceneDuration: 6,
      cutOnBeat: true,
      energyLevel: 'fast',
    },
  },
  {
    name: 'Documentary',
    description: 'Slow, cinematic style with elegant text and long scenes',
    textStyles: [
      {
        id: '1',
        name: 'Title Card',
        font: 'Georgia, serif',
        size: 56,
        color: '#f0f0f0',
        position: 'center',
        animation: 'fadeIn',
        timing: { inDuration: 30, holdDuration: 90, outDuration: 30 },
        fontWeight: 'normal',
        textAlign: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        padding: 40,
        borderRadius: 8,
      },
      {
        id: '2',
        name: 'Quote Text',
        font: 'Georgia, serif',
        size: 42,
        color: '#ffffff',
        position: 'center',
        animation: 'typewriter',
        timing: { inDuration: 60, holdDuration: 120, outDuration: 20 },
        fontWeight: 'light',
        textAlign: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        padding: 35,
        borderRadius: 6,
      },
    ],
    transitions: {
      type: 'dissolve',
      duration: 20,
      frequency: 2, // 2 cuts per minute
    },
    brollPatterns: {
      insertFrequency: 45,
      duration: 8,
      transitionIn: 'dissolve',
      transitionOut: 'dissolve',
    },
    pacing: {
      avgSceneDuration: 15,
      cutOnBeat: false,
      energyLevel: 'slow',
    },
  },
  {
    name: 'Vlog Style',
    description: 'Casual, energetic style with playful animations',
    textStyles: [
      {
        id: '1',
        name: 'Pop-up Text',
        font: 'Comic Sans MS, cursive',
        size: 48,
        color: '#ffff00',
        position: 'topRight',
        animation: 'bounce',
        timing: { inDuration: 8, holdDuration: 30, outDuration: 8 },
        fontWeight: 'bold',
        textAlign: 'right',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: 20,
        borderRadius: 20,
      },
      {
        id: '2',
        name: 'Subtitle',
        font: 'Arial, sans-serif',
        size: 38,
        color: '#ffffff',
        position: 'lowerThird',
        animation: 'slideUp',
        timing: { inDuration: 10, holdDuration: 50, outDuration: 10 },
        fontWeight: 'normal',
        textAlign: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        padding: 15,
        borderRadius: 10,
      },
    ],
    transitions: {
      type: 'cut',
      duration: 0,
      frequency: 6, // 6 cuts per minute
    },
    brollPatterns: {
      insertFrequency: 20,
      duration: 3,
      transitionIn: 'cut',
      transitionOut: 'fade',
    },
    pacing: {
      avgSceneDuration: 5,
      cutOnBeat: true,
      energyLevel: 'fast',
    },
  },
];
